language: rust
sudo: false
rust:
  - nightly

os:
  - linux
  - osx

env:
  - FEATURES=""
  - FEATURES="heap_size"

script:
  - cargo build --verbose --features "$FEATURES"
  - cargo test --verbose --features "$FEATURES"

notifications:
  webhooks: http://build.servo.org:54856/travis
