[package]
name = "ipc-channel"
version = "0.5.0"
description = "A multi-process implementation for multi-producer, single-consumer channels."
license = "MIT / Apache-2.0"
authors = ["The Servo Project Developers"]

[lib]
name = "ipc_channel"
path = "lib.rs"

[dependencies]
bincode = "0.6"
lazy_static = "0.2"
libc = "0.2.12"
rand = "0.3"
serde = "0.8"
uuid = {version = "0.3", features = ["v4"]}

[dev-dependencies]
crossbeam = "0.2"
